# Generated by Django 5.2.8 on 2025-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
